version: '3.4'

services:
  db:
    image: mysql
    networks:
      - docker-network

  back:
    image: ${DOCKER_REGISTRY-}back
    build:
      context: .
      dockerfile: src/ClientBarometer/Dockerfile
    networks:
      - docker-network

  front:
    image: node:12-alpine
    command: sh -c "CI=true yarn start"
    working_dir: /app
    networks:
      - docker-network

networks:
  docker-network:
     driver: bridge