version: '3.4'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=client-barometer
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
        - './db:/var/lib/mysql'
    ports:
      - "3306:3306"

  back:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Front__Url=http://front:3000
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  front:
    volumes:
      - ./src/Front:/app
    ports:
      - 3000:3000

  ngrok:
    environment:
      - NGROK_AUTH=${NGROK_TOKEN}
      - NGROK_LOOK_DOMAIN=${BACK_URL}
      - NGROK_PORT=${BACK_PORT}
      - NGROK_DEBUG=true
    ports:
      - "6020:4040"

  predictor:
    ports:
      - "5010:5000"